name: Deploy Featurevisor

on:
  workflow_dispatch:

jobs:
  deploy-featurevisor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Lint
        run: npm run lint

      - name: Test specs
        run: npm run test

      - name: Build
        run: npm run build

      - name: Export
        run: npm run export

      - name: Deploy to AWS
        run: aws s3 sync out s3://prod-test-app-features-bucket